services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flash_cards
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  springboot:
    container_name: springboot
    build:
      context: ./springboot-flash-cards
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres

  angular_nginx:
    container_name: angular_nginx
    build:
      context: ./angular-flash-cards
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - springboot
    links:
      - springboot

volumes:
  postgres:
